language: node_js
node_js:
    - lts/*
install:
  - yarn --frozen-lockfile
  - gem install mdl
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn lint
  - yarn test --coverageDirectory=. --coverage
  - yarn typecheck
  - mdl README.md
  - mdl docs/
after_script:
  - ./cc-test-reporter after-build --coverage-input-type=lcov --exit-code $TRAVIS_TEST_RESULT
